FROM node:20-alpine AS builder
WORKDIR /app

# Copy root configs
COPY package*.json ./
COPY packages ./packages
COPY apps/api/package*.json ./apps/api/
COPY apps/api/prisma ./apps/api/prisma

# Install dependencies
RUN npm ci

# Copy source code
COPY apps/api ./apps/api
COPY packages ./packages

# Build shared types package first
RUN npm run build --workspace=@espejos/shared-types

# Generate Prisma Client & Build
WORKDIR /app/apps/api
RUN npx prisma generate

EXPOSE 3000

ENV NODE_ENV=production
ENV PORT=3000

CMD ["npx", "tsx", "src/server.ts"]
